# Generated by Django 4.1.4 on 2022-12-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(upload_to="media/%Y/%m/%d/"),
        ),
    ]
