# Generated by Django 4.1.4 on 2022-12-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_alter_news_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="most_popular",
            field=models.BooleanField(default=False),
        ),
    ]
