# Generated by Django 4.1.4 on 2022-12-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_news_most_popular"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-published_date"]},
        ),
        migrations.RemoveField(
            model_name="news",
            name="created_time",
        ),
    ]
