# Generated by Django 4.1.4 on 2022-12-24 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_alter_news_options_remove_news_created_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="redactor",
            name="image",
            field=models.ImageField(default="", upload_to="media/%Y/%m/%d/"),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="news",
            name="publishers",
        ),
        migrations.AddField(
            model_name="news",
            name="publishers",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
