# Generated by Django 4.1.4 on 2022-12-24 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_redactor_image_remove_news_publishers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="publishers",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
