# Generated by Django 4.1.4 on 2022-12-24 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_alter_news_publishers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="publishers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
