# Generated by Django 4.1.4 on 2022-12-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_alter_news_publishers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="image",
            field=models.ImageField(null=True, upload_to="media/%Y/%m/%d/"),
        ),
    ]
