# Generated by Django 4.1.4 on 2022-12-26 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0012_redactor_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(null=True, upload_to="media/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="news",
            name="publishers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
