# Generated by Django 4.1.4 on 2022-12-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0013_alter_news_image_alter_news_publishers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/%Y/%m/%d/"),
        ),
    ]
