# Generated by Django 4.1.4 on 2022-12-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0015_alter_redactor_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(default=1, upload_to="media/%Y/%m/%d/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="redactor",
            name="image",
            field=models.ImageField(null=True, upload_to="media/%Y/%m/%d/"),
        ),
    ]
