# Generated by Django 4.1.4 on 2022-12-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0016_alter_news_image_alter_redactor_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/%Y/%m/%d/"),
        ),
    ]
