# Generated by Django 4.1.4 on 2022-12-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0019_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(default=1, upload_to="media/%Y/%m/%d/"),
            preserve_default=False,
        ),
    ]
